import { millisecondsToMmSs } from '@/lib/utils';
import type { SliderValue, TrackAttribute } from '@/types';
import { z } from 'zod';

const formatDuration = (value: SliderValue): string => {
  const min = millisecondsToMmSs(value[0]);
  const max = millisecondsToMmSs(value[1]!);
  return `${min}–${max}`;
};

export const TRACK_ATTRIBUTES: Array<TrackAttribute> = [
  {
    id: 'acousticness',
    label: 'Acousticness',
    description:
      'A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic.',
    min: 0,
    max: 1,
    defaultValue: [0, 0.5, 1],
    step: 0.01,
  },
  {
    id: 'danceability',
    label: 'Danceability',
    description:
      'Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.',
    min: 0,
    max: 1,
    defaultValue: [0, 0.5, 1],
    step: 0.01,
  },
  {
    id: 'duration_ms',
    label: 'Duration',
    description: 'The duration of the track in milliseconds.',
    min: 0,
    max: 600_000,
    step: 1000,
    defaultValue: [0, 600_000],
    formatter: formatDuration,
  },
  {
    id: 'energy',
    label: 'Energy',
    description:
      'Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.',
    min: 0,
    max: 1,
    defaultValue: [0, 0.5, 1],
    step: 0.01,
  },
  {
    id: 'instrumentalness',
    label: 'Instrumentalness',
    description:
      'Predicts whether a track contains no vocals. "Ooh" and "aah" sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly "vocal". The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0.',
    min: 0,
    max: 1,
    defaultValue: [0, 0.5, 1],
    step: 0.01,
  },
  {
    id: 'key',
    label: 'Key',
    description:
      'The key the track is in. Integers map to pitches using standard Pitch Class notation. E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1.',
    min: 0,
    max: 11,
    step: 1,
    defaultValue: [0, 5, 11],
  },
  {
    id: 'liveness',
    label: 'Liveness',
    description:
      'Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.',
    min: 0,
    max: 1,
    defaultValue: [0, 0.5, 1],
    step: 0.01,
  },
  {
    id: 'loudness',
    label: 'Loudness',
    description:
      'The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typically range between -60 and 0 db.',
    min: -70,
    max: 0,
    step: 1,
    defaultValue: [-70, -35, 0],
    unit: 'db',
  },
  {
    id: 'mode',
    label: 'Mode',
    description:
      'Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0.',
    min: 0,
    max: 1,
    defaultValue: [0],
    step: 1,
    formatter: (value) => ['Minor', 'Major'][value[0]] ?? 'Minor',
  },
  {
    id: 'popularity',
    label: 'Popularity',
    description: `The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular. The artist's popularity is calculated from the popularity of all the artist's tracks.`,
    min: 0,
    max: 100,
    defaultValue: [0, 50, 100],
    step: 1,
  },
  {
    id: 'speechiness',
    label: 'Speechiness',
    description:
      'Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.',
    min: 0,
    max: 1,
    defaultValue: [0, 0.5, 1],
    step: 0.01,
  },
  {
    id: 'tempo',
    label: 'Tempo',
    description:
      'The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.',
    min: 0,
    max: 200,
    defaultValue: [0, 100, 200],
    step: 1,
  },
  {
    id: 'time_signature',
    label: 'Time Signature',
    description:
      'An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of "3/4", to "7/4".',
    min: 3,
    max: 7,
    step: 1,
    defaultValue: [3, 5, 7],
    formatter: (value) => `${value[1]}\u2044${'7'}`,
  },
  {
    id: 'valence',
    label: 'Valence',
    description:
      'A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).',
    min: 0,
    max: 1,
    defaultValue: [0, 0.5, 1],
    step: 0.01,
  },
];

export const GENRES = [
  { value: 'acoustic', label: 'Acoustic' },
  { value: 'afrobeat', label: 'Afrobeat' },
  { value: 'alt-rock', label: 'Alt Rock' },
  { value: 'alternative', label: 'Alternative' },
  { value: 'ambient', label: 'Ambient' },
  { value: 'anime', label: 'Anime' },
  { value: 'black-metal', label: 'Black Metal' },
  { value: 'bluegrass', label: 'Bluegrass' },
  { value: 'blues', label: 'Blues' },
  { value: 'bossanova', label: 'Bossanova' },
  { value: 'brazil', label: 'Brazil' },
  { value: 'breakbeat', label: 'Breakbeat' },
  { value: 'british', label: 'British' },
  { value: 'cantopop', label: 'Cantopop' },
  { value: 'chicago-house', label: 'Chicago House' },
  { value: 'children', label: 'Children' },
  { value: 'chill', label: 'Chill' },
  { value: 'classical', label: 'Classical' },
  { value: 'club', label: 'Club' },
  { value: 'comedy', label: 'Comedy' },
  { value: 'country', label: 'Country' },
  { value: 'dance', label: 'Dance' },
  { value: 'dancehall', label: 'Dancehall' },
  { value: 'death-metal', label: 'Death Metal' },
  { value: 'deep-house', label: 'Deep House' },
  { value: 'detroit-techno', label: 'Detroit Techno' },
  { value: 'disco', label: 'Disco' },
  { value: 'disney', label: 'Disney' },
  { value: 'drum-and-bass', label: 'Drum and Bass' },
  { value: 'dub', label: 'Dub' },
  { value: 'dubstep', label: 'Dubstep' },
  { value: 'edm', label: 'Edm' },
  { value: 'electro', label: 'Electro' },
  { value: 'electronic', label: 'Electronic' },
  { value: 'emo', label: 'Emo' },
  { value: 'folk', label: 'Folk' },
  { value: 'forro', label: 'Forro' },
  { value: 'french', label: 'French' },
  { value: 'funk', label: 'Funk' },
  { value: 'garage', label: 'Garage' },
  { value: 'german', label: 'German' },
  { value: 'gospel', label: 'Gospel' },
  { value: 'goth', label: 'Goth' },
  { value: 'grindcore', label: 'Grindcore' },
  { value: 'groove', label: 'Groove' },
  { value: 'grunge', label: 'Grunge' },
  { value: 'guitar', label: 'Guitar' },
  { value: 'happy', label: 'Happy' },
  { value: 'hard-rock', label: 'Hard Rock' },
  { value: 'hardcore', label: 'Hardcore' },
  { value: 'hardstyle', label: 'Hardstyle' },
  { value: 'heavy-metal', label: 'Heavy Metal' },
  { value: 'hip-hop', label: 'Hip-Hop' },
  { value: 'holidays', label: 'Holidays' },
  { value: 'honky-tonk', label: 'Honky Tonk' },
  { value: 'house', label: 'House' },
  { value: 'idm', label: 'Idm' },
  { value: 'indian', label: 'Indian' },
  { value: 'indie', label: 'Indie' },
  { value: 'indie-pop', label: 'Indie Pop' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'iranian', label: 'Iranian' },
  { value: 'j-dance', label: 'J Dance' },
  { value: 'j-idol', label: 'J Idol' },
  { value: 'j-pop', label: 'J Pop' },
  { value: 'j-rock', label: 'J Rock' },
  { value: 'jazz', label: 'Jazz' },
  { value: 'k-pop', label: 'K-pop' },
  { value: 'kids', label: 'Kids' },
  { value: 'latin', label: 'Latin' },
  { value: 'latino', label: 'Latino' },
  { value: 'malay', label: 'Malay' },
  { value: 'mandopop', label: 'Mandopop' },
  { value: 'metal', label: 'Metal' },
  { value: 'metal-misc', label: 'Metal Misc' },
  { value: 'metalcore', label: 'Metalcore' },
  { value: 'minimal-techno', label: 'Minimal Techno' },
  { value: 'movies', label: 'Movies' },
  { value: 'mpb', label: 'Mpb' },
  { value: 'new-age', label: 'New Age' },
  { value: 'new-release', label: 'New Release' },
  { value: 'opera', label: 'Opera' },
  { value: 'pagode', label: 'Pagode' },
  { value: 'party', label: 'Party' },
  { value: 'philippines-opm', label: 'Philippines OPM' },
  { value: 'piano', label: 'Piano' },
  { value: 'pop', label: 'Pop' },
  { value: 'pop-film', label: 'Pop Film' },
  { value: 'post-dubstep', label: 'Post Dubstep' },
  { value: 'power-pop', label: 'Power Pop' },
  { value: 'progressive-house', label: 'Progressive House' },
  { value: 'psych-rock', label: 'Psych Rock' },
  { value: 'punk', label: 'Punk' },
  { value: 'punk-rock', label: 'Punk Rock' },
  { value: 'r-n-b', label: 'RnB' },
  { value: 'rainy-day', label: 'Rainy Fay' },
  { value: 'reggae', label: 'Reggae' },
  { value: 'reggaeton', label: 'Reggaeton' },
  { value: 'road-trip', label: 'Road Trip' },
  { value: 'rock', label: 'Rock' },
  { value: 'rock-n-roll', label: 'Rock n Roll' },
  { value: 'rockabilly', label: 'Rockabilly' },
  { value: 'romance', label: 'Romance' },
  { value: 'sad', label: 'Sad' },
  { value: 'salsa', label: 'Salsa' },
  { value: 'samba', label: 'Samba' },
  { value: 'sertanejo', label: 'Sertanejo' },
  { value: 'show-tunes', label: 'Show Tunes' },
  { value: 'singer-songwriter', label: 'Singer Songwriter' },
  { value: 'ska', label: 'Ska' },
  { value: 'sleep', label: 'Sleep' },
  { value: 'songwriter', label: 'Songwriter' },
  { value: 'soul', label: 'Soul' },
  { value: 'soundtracks', label: 'Soundtracks' },
  { value: 'spanish', label: 'Spanish' },
  { value: 'study', label: 'Study' },
  { value: 'summer', label: 'Summer' },
  { value: 'swedish', label: 'Swedish' },
  { value: 'synth-pop', label: 'Synth Pop' },
  { value: 'tango', label: 'Tango' },
  { value: 'techno', label: 'Techno' },
  { value: 'trance', label: 'Trance' },
  { value: 'trip-hop', label: 'Trip Hop' },
  { value: 'turkish', label: 'Turkish' },
  { value: 'work-out', label: 'Work Out' },
  { value: 'world-music', label: 'World Music' },
];

export const TrackAttributesSchema = z.object({
  seed_artists: z
    .union([z.array(z.string()), z.string()])
    .optional()
    .transform((v) => (typeof v === 'string' ? [v] : v))
    .default([]),
  seed_tracks: z
    .union([z.array(z.string()), z.string()])
    .optional()
    .transform((v) => (typeof v === 'string' ? [v] : v))
    .default([]),
  seed_genres: z
    .union([z.array(z.string()), z.string()])
    .optional()
    .transform((v) => (typeof v === 'string' ? [v] : v))
    .default([]),
  min_acousticness: z.coerce.number().optional(),
  target_acousticness: z.coerce.number().optional(),
  max_acousticness: z.coerce.number().optional(),
  min_danceability: z.coerce.number().optional(),
  max_danceability: z.coerce.number().optional(),
  target_danceability: z.coerce.number().optional(),
  min_duration_ms: z.coerce.number().optional(),
  max_duration_ms: z.coerce.number().optional(),
  target_duration_ms: z.coerce.number().optional(),
  min_energy: z.coerce.number().optional(),
  max_energy: z.coerce.number().optional(),
  target_energy: z.coerce.number().optional(),
  min_instrumentalness: z.coerce.number().optional(),
  max_instrumentalness: z.coerce.number().optional(),
  target_instrumentalness: z.coerce.number().optional(),
  min_key: z.coerce.number().optional(),
  max_key: z.coerce.number().optional(),
  target_key: z.coerce.number().optional(),
  min_liveness: z.coerce.number().optional(),
  max_liveness: z.coerce.number().optional(),
  target_liveness: z.coerce.number().optional(),
  min_loudness: z.coerce.number().optional(),
  max_loudness: z.coerce.number().optional(),
  target_loudness: z.coerce.number().optional(),
  min_mode: z.coerce.number().optional(),
  max_mode: z.coerce.number().optional(),
  target_mode: z.coerce.number().optional(),
  min_popularity: z.coerce.number().optional(),
  max_popularity: z.coerce.number().optional(),
  target_popularity: z.coerce.number().optional(),
  min_speechiness: z.coerce.number().optional(),
  max_speechiness: z.coerce.number().optional(),
  target_speechiness: z.coerce.number().optional(),
  min_tempo: z.coerce.number().optional(),
  max_tempo: z.coerce.number().optional(),
  target_tempo: z.coerce.number().optional(),
  min_time_signature: z.coerce.number().optional(),
  max_time_signature: z.coerce.number().optional(),
  target_time_signature: z.coerce.number().optional(),
  min_valence: z.coerce.number().optional(),
  max_valence: z.coerce.number().optional(),
  target_valence: z.coerce.number().optional(),
  view: z.enum(['grid', 'list']).optional().default('grid'),
});
